destination: ./_site
auto:        false
server_port: 4000
markdown:    maruku
permalink:   date
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex

pygments: true
lsi: false
paginate: 20

